apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: baskit

resources:
  - ./deploy.yaml
  - ./svc.yaml
  - ./servicemonitor.yaml
  - ./secret-sealed.yaml
  - ./ghcr-secret-sealed.yaml
