apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dotbintask

resources:
  - ./pvc.yaml
  - ./deploy.yaml
  - ./svc.yaml
  - ./ing.yaml
  - ./secret-sealed.yaml

labels:
- includeSelectors: true
  pairs:
    app: dotbintask

